### ISSUE TITLE
not ready for python3

### ISSUE THREAD

**Issue by ReimarBauer** [conda-forge/pykml-feedstock#6]
the pypi.io version tries an import of urllib2 for urlopen.
At least this version is not compatible yet with py3.
There are many forks on github, not sure which one is activily maintained.

**Comment by ocefpaf** [comment]
I am away from my laptop. If you want to fix that before I get back all that is needed is a PR adding `skip: True # [py3k]` and a [rerender](http://conda-forge.github.io/docs/conda_smithy.html).

**Comment by ReimarBauer** [comment]
I Can do so tom.

Filipe <notifications@github.com> schrieb am Di., 16. Mai 2017, 19:43:
